version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: [ollama_data:/root/.ollama]
    restart: always

  litellm-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: litellm
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: mysecret
    volumes: [litellm_db_data:/var/lib/postgresql/data]

  litellm:
    image: ghcr.io/berriai/litellm:main-v1.67.4-stable
    ports: ["4000:4000"]        
    depends_on: [ollama, litellm-db]
    volumes:
      - ./litellm.config.yaml:/app/litellm.config.yaml
    environment:
      - LITELLM_MASTER_KEY=sk-1234
      - LITELLM_SALT_KEY=sk-change-me-once
      - DATABASE_URL=postgresql://litellm:mysecret@litellm-db:5432/litellm
      - PORT=4000
      - STORE_MODEL_IN_DB=True
      - UI_USERNAME=admin
      - UI_PASSWORD=changeme
    command:
      - "--config"        
      - "/app/litellm.config.yaml"
      - "--host"          
      - "0.0.0.0"
      - "--port"          
      - "4000"
      - "--num_workers"   
      - "2"

  mcp:
    build:
      context: .
      dockerfile: dockerfile.mcp
    depends_on: [litellm]
    ports: ["8050:8050"]
    environment:
      LITELLM_BASE_URL: "http://litellm:4000"
      LITELLM_API_KEY:  "sk-1234"
      PORT: "8080"
    restart: unless-stopped

volumes:
  ollama_data:
  litellm_db_data:

