FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY ./pyproject.toml .

RUN  uv pip install -r pyproject.toml --system --no-cache-dir

COPY ../server.py /app/

ENV PORT=8080 \
    LITELLM_BASE_URL=http://litellm:4000 \
    LITELLM_API_KEY=sk-1234       

CMD ["python", "server.py"]